### ISSUE TITLE
About cube faces disappearing

### ISSUE THREAD

**Issue by daniportela** [bobangajicsm/react-portfolio-website#2]
Hey! I was following along your YouTube tutorial and couldn't help but notice some faces on the animated cube in the About page disappeared. I couldn't find a fix for it, and I thought maybe it was a browser problem (I tried opening the website in many other devices, all using Chrome, and it still doesn't display properly). I thought I would post it here to maybe find a solution!

**Comment by lucasnatal1** [comment]
> Hey! I was following along your YouTube tutorial and couldn't help but notice some faces on the animated cube in the About page disappeared. I couldn't find a fix for it, and I thought maybe it was a browser problem (I tried opening the website in many other devices, all using Chrome, and it still doesn't display properly). I thought I would post it here to maybe find a solution!

Same problem here

**Comment by mattieramos** [comment]
Yes, I as well am getting the same issue regarding the spinning cube.

**Comment by hoycode** [comment]
I'm having the exact same problem as you.

**Comment by pesova** [comment]
true, notice in his tutorial, some cube face was also disappearing

**Comment by bobangajicsm** [comment]
I'll try to address it

**Comment by SahuUtkarsh03** [comment]
@bobangajicsm Do you got the solution or know how to correct it?

**Comment by bobangajicsm** [comment]
This has been fixed, pull the latest code
