### ISSUE TITLE
page is not loading

### ISSUE THREAD

**Issue by Boby900** [bobangajicsm/react-portfolio-website#20]
hi @bobangajicsm ,
I ran the local development on the server, that is running but returning only blank page.
Can you help me with that 
![Screenshot (14)](https://user-images.githubusercontent.com/111265239/209138385-71c224ff-26a9-4cee-9c8a-2b1512360302.png)

**Comment by Ishygit** [comment]
try  running **npm run dev** in the terminal(powershell). You will get a link to the server

**Comment by maligaurav947** [comment]
if you are downloading From Github After Opening in vscode try running in terminal `npm install` in the Project directory

**Comment by chienhsiang-hung** [comment]
Hi @Boby900 ,
Have you found the solution? I have the same issue here.
