### ISSUE TITLE
all links from sidebar updating URL but not loading  pages 

### ISSUE THREAD

**Issue by EngDeaa** [bobangajicsm/react-portfolio-website#6]
If I try to click on contact or mail link from the sidebar,  it's updating the URL above but not loading the pages(just blank page shown) until I refresh the page then it works good
Any suggestions ? Thank you very much

**Comment by daniportela** [comment]
There is the following piece of code in many components:

` useEffect(() => {
    return setTimeout(() => {
      setLetterClass('text-animate-hover')
    }, 4000)
  }, [])`

Remove the `return` keyword in all of them. `setTimeOut` is not supposed to return anything. That fixed it for me.

**Comment by EngDeaa** [comment]
thank very much , it takes me 4 days and i didn't find the solution but now it works 

i have another problem the cubic in about me page some times show the images some times it disapear what could be the problem ??
> There is the following piece of code in many components:
> 
> ` useEffect(() => { return setTimeout(() => { setLetterClass('text-animate-hover') }, 4000) }, [])`
> 
> Remove the `return` keyword in all of them. `setTimeOut` is not supposed to return anything. That fixed it for me.

**Comment by bobangajicsm** [comment]
> thank very much , it takes me 4 days and i didn't find the solution but now it works
> 
> i have another problem the cubic in about me page some times show the images some times it disapear what could be the problem ??
> 
> > There is the following piece of code in many components:
> > ` useEffect(() => { return setTimeout(() => { setLetterClass('text-animate-hover') }, 4000) }, [])`
> > Remove the `return` keyword in all of them. `setTimeOut` is not supposed to return anything. That fixed it for me.

There is another issue opened for it. Thanks!
