### ISSUE TITLE
How can we change the Logo letter from S to another letter 

### ISSUE THREAD

**Issue by EngDeaa** [bobangajicsm/react-portfolio-website#7]
is is easy to change the logo letter ?

**Comment by DeveloperX104** [comment]
Kindly explore a preferable graphics editing software.

**Comment by EngDeaa** [comment]
> Kindly explore a preferable graphics editing software.

could you please suggest any one easy to do it

**Comment by Benmuiruri** [comment]
@EngDeaa You can create a Letter with Canva then use an online converter to convert the letter from png to svg

**Comment by bobangajicsm** [comment]
This is not an issue with the codebase
