### ISSUE TITLE
useEffect error

### ISSUE THREAD

**Issue by PoovendhanNandhu** [bobangajicsm/react-portfolio-website#9]
86 Warning: useEffect must not return anything besides a function, which is used for clean-up. You returned: 18

I am getting this error when I implemented the useEffect function to animate the letters.

![errors12](https://user-images.githubusercontent.com/94177343/169358439-b533f63c-97d5-46fe-b5b2-ff9dea1fe487.png)
![code1](https://user-images.githubusercontent.com/94177343/169358443-2ae8e24d-bad1-4f23-9a9f-461e09389b5a.png)
s

**Comment by kirizarry47** [comment]
how did you resolve the useEffect error?

**Comment by PoovendhanNandhu** [comment]
> how did you resolve the useEffect error?
> 

so we shouldn't use useEffect inside the home function (in this case). We shouldn't include any superstates insde the main function.

**Comment by Ankitv003** [comment]
it can also be resolved using a cleanup function, like this

useEffect(() => {
  const timeoutId = setTimeout(() => {
    setLetterClass('text-animate-hover');
  }, 4000);

  // Cleanup function to clear the timeout if the component unmounts or the effect is re-triggered
  return () => {
    clearTimeout(timeoutId);
  };
}, []);

**Comment by Ankitv003** [comment]
> how did you resolve the useEffect error?

it can also be resolved using a cleanup function, like this

useEffect(() => {
const timeoutId = setTimeout(() => {
setLetterClass('text-animate-hover');
}, 4000);

// Cleanup function to clear the timeout if the component unmounts or the effect is re-triggered
return () => {
clearTimeout(timeoutId);
};
}, []);
